### ISSUE TITLE
Add "Native" Python Type Support to Write State

### ISSUE THREAD

**Issue by shihaocao** [pathfinder-for-autonomous-navigation/FlightSoftware#255]
- ~Have Ptest automatically call cycle as an option~
- Have Ptest take *args
- Support for multiple arg types

__EDIT:__ See @kkrol27's comment below.

**Comment by tanishqaggarwal** [comment]
See addition of cycle() option on the `prop_driver_case` branch

**Comment by tanishqaggarwal** [comment]
Could you clarify what you mean by *args?

**Comment by shihaocao** [comment]
@kkrol27 Do you mind if you actually clarify? I'm actually not too familiar with optional arguments in python.

**Comment by kkrol27** [comment]
Here I was mainly talking about better support for vectors and potentially look into supporting "native" Python types as opposed to always having to pass strings to things (see #251). Changes would mainly affect override and write state and would be backwards compatible.

For example, when writing a vector to a state instead of doing this:

    self.sim.flight_controller.write_state("adcs_cmd.rwa_speed_cmd", "0, 0, 0")

we could make this possible:

   self.sim.flight_controller.write_state("adcs_cmd.rwa_speed_cmd", 0.0, 0.0, 0.0)

We could add native support for types like booleans:

    self.sim.flight_controller.write_state("dcdc.ADCSMotor_cmd", True)

instead of:

    self.sim.flight_controller.write_state("dcdc.ADCSMotor_cmd", "true")

These changes would be pretty easy to implement by moving to a `*args` and `**kwargs` paradigm. I'm totally happy to tackle this tomorrow/this weekend if it sounds like good changes! Should probably get more involved in ptest anyway.
