### ISSUE TITLE
Check that subsystems respond gracefully to power loss conditions

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#495]
Power cycles and power dropouts necessitate more careful tracking of these bugs.
- Power cycling creates a delay between an output going off and coming back online

For example:
- QuakeManager needs to check the "powered" flag prior to doing comms
- Do ADCS, prop, and Piksi have this problem? #487 tracks an ADCS issue where it takes some time to ramp up. But the other issues don't have associated tickets.

**Comment by shihaocao** [comment]
@piksi 

Piksi should be robust to power loss at anytime and resumption at any time. With regard to getting piksi CT up to date, this ticket is relevant: #98 
#98

**Comment by tanishqaggarwal** [comment]
Prop: we need to add is_functional checks before can_enter for every state, not just IDLE.
Quake: We should have the QuakeFaultHandler handle the QuakeManager state before and after the powercycle.

**Comment by shihaocao** [comment]
ADCS:

Modifications:
Add loop(); once before the interrupts in main.cpp in the setup() function.

For each of the following cases, check that the ADCS works as intended before and after. Take care to watch for any DCDC + motor interplay as we saw some before. We initiate/execute each of these cases at the software level using the same state machines.

- Whole satellite reboot
- ADCS reboot only (nevermind since we dont ever autonomously reboot the ADCS, if we did, we'd probably just reboot the whole sat)

^Probably a manual test + documentation of behavior
