### ISSUE TITLE
PTest case for power loss conditions 

### ISSUE THREAD

**Issue by afoarce** [pathfinder-for-autonomous-navigation/FlightSoftware#509]
Since the enhancements to Quake, Quake Fault Handler, Prop, and ADCS can have effects across subsystems, we should create a ptest case to verify that things like power-cycling and state switches are behaving as expected and we are not having adverse effects.

**Comment by 18kudlugim** [comment]
Behavior tested in this PTest case is based on the assumption that the QuakeFaultHandler can only power cycle when the radio is in the Wait state. After more examination, we determined that this underlying behavior needed to be changed. 

When the QuakeFaultHandler is about to power cycle, it should instead be setting the QuakeManager to be in the Wait state. Since the underlying assumptions regarding this PTest have since changed, we need to first address the changes that need to be made to the QuakeFaultHandler implementation and then return to this ticket.
