### ISSUE TITLE
Cannot read solar panel charging currents when testing with flight units

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#572]
We were not able to get charging currents for the solar panels when testing with the flight units. Unclear if we're just reading the wrong state fields (unlikely), or if some mode setting is not correct. We did see the vboost voltages change.

May want to reach out to Gomspace to ask them?

**Comment by kylekrol** [comment]
If we can verify that the battery actually charges that would be sufficient to close this ticket.

**Comment by shihaocao** [comment]
LEADER DATA:
![Screenshot from 2021-02-10 16-22-19](https://user-images.githubusercontent.com/14984742/107574363-a323fb00-6bbc-11eb-9d1a-37718ef6546d.png)

**Comment by shihaocao** [comment]
FOLLOWER DATA:
![Screenshot from 2021-02-10 16-21-00](https://user-images.githubusercontent.com/14984742/107574541-d49cc680-6bbc-11eb-9922-e9070bebd78c.png)

**Comment by shihaocao** [comment]
Since all three curin's show response, that shows us that all 3 boost converters have the ability to draw power, on both satellites.

Further, since cursun is positive at some point through both tests, that gives us confidence that the satellites will be able to charge in space while the satellite is on.
